### ISSUE TITLE
Can't interrupt blocking accept

### ISSUE THREAD

**Issue by gregw** [jnr/jnr-unixsocket#21]
A blocking call to accept cannot be interrupted, not even if the channel is closed.   This is demonstrated by the following code:

``` java
import java.io.File;
import java.io.IOException;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicBoolean;

import jnr.unixsocket.UnixServerSocketChannel;
import jnr.unixsocket.UnixSocketAddress;

public class UnixSocketAcceptInterrupt
{
    public static void main(String... args) throws Exception
    {
        File file = new File("/tmp/test.sock");
        if (file.exists())
            file.delete();

        final UnixServerSocketChannel channel = UnixServerSocketChannel.open();
        channel.socket().bind(new UnixSocketAddress(file));

        final AtomicBoolean run = new AtomicBoolean(true);
        final CountDownLatch start = new CountDownLatch(1);
        final CountDownLatch complete = new CountDownLatch(1);
        Thread accept = new Thread()
        {
            @Override public void run()
            {
                start.countDown();
                try
                {
                    while(run.get())
                    {
                        try
                        {
                            channel.accept();
                            System.err.println("accepted");
                        }
                        catch (IOException e)
                        {
                            e.printStackTrace();
                        }
                    }
                }
                finally
                {
                    complete.countDown();
                }
            }
        };
        accept.setDaemon(true);
        accept.start();
        if (!start.await(5,TimeUnit.SECONDS))
            System.err.println("Timeout waiting for start");

        Thread.sleep(1000);

        run.set(false);
        accept.interrupt();
        if (!complete.await(5,TimeUnit.SECONDS))
            System.err.println("Timeout waiting for complete");

        channel.close();
        accept.interrupt();
        if (!complete.await(5,TimeUnit.SECONDS))
            System.err.println("Timeout waiting for complete after close");
    }
}
```

**Comment by felfert** [comment]
AFAIK, This is the documented behaviour of java.nio.channels.spi.AbstractInterruptibleChannel.
You need to use begin()/end() pairs, if you want to interrupt the thread.
See https://docs.oracle.com/javase/7/docs/api/java/nio/channels/spi/AbstractInterruptibleChannel.html#be

**Comment by gregw** [comment]
@felfert but begin/end are protected methods, so I can't call them directly.  Surely it is the JNR implementation of UnixServerSocketChannel#accept that should be calling them?

**Comment by gregw** [comment]
Specifically, shouldn't [this line](https://github.com/jnr/jnr-unixsocket/blob/master/src/main/java/jnr/unixsocket/UnixServerSocketChannel.java#L56) be wrapped in begin/end pairs?

**Comment by headius** [comment]
@gregw I think you're right. Can you help us patch this?

**Comment by gregw** [comment]
@headius #25 is a PR that adds begin/end calls.    It makes it a little bit better, but doesn't generally fix the problem? At least not on `Linux Tile440 4.2.0-30-generic #36-Ubuntu SMP Fri Feb 26 00:58:07 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by headius** [comment]
Fix this for 0.14.

**Comment by leifwalsh** [comment]
I think the way to do `accept()` with an interrupt or timeout is to call `select()` first, check if the socket is ready, and then call `accept()` knowing there's a connection to accept.  You could set things up so that one of the sockets passed to `select()` is something that a thread wanting to interrupt it could close or otherwise signal, separate from the socket you're actually trying to accept on, and you could implement a version of the api with a timeout.

**Comment by swankjesse** [comment]
Fixed in https://github.com/jnr/jnr-unixsocket/pull/65
