### ISSUE TITLE
support for SOCK_DGRAM

### ISSUE THREAD

**Issue by yuanwang-wf** [jnr/jnr-unixsocket#22]
is there any plan to support DGRAM socket

**Comment by headius** [comment]
There's no plan, but I want to do so. Can you help?

**Comment by yuanwang-wf** [comment]
yes, I can send a pull request for that, just my C/ Unix skill is not great.

**Comment by headius** [comment]
@yuanwang-wf Give it a shot, we'll work through it together :-)

**Comment by headius** [comment]
@yuanwang-wf Still out there?

**Comment by yuanwang-wf** [comment]
@headius yes

**Comment by felfert** [comment]
This can be closed.
I have implemented everything implemented in #35 together with general refactoring (already functional, yet some set/getOption stuff unimplemented - will do that during the next days ...).
