### ISSUE TITLE
UnixServerSocketChannel.accept() should return null in non-blocking mode

### ISSUE THREAD

**Issue by normanmaurer** [jnr/jnr-unixsocket#31]
`UnixServerSocketChannel.accept()` should return null in non-blocking mode when there are no more client channels to accept. At the moment it throws a Exception which is wasteful as this is expensive. 

https://github.com/jnr/jnr-unixsocket/blob/master/src/main/java/jnr/unixsocket/UnixServerSocketChannel.java#L59

**Comment by headius** [comment]
Agreed. Fixing. PR a test for me?
