### ISSUE TITLE
add some keywords

### ISSUE THREAD

**Issue by neuhaus** [jnr/jnr-unixsocket#32]
I didn't find this project at first because I was looking for "unix domain sockets" (the official term) and neither the project description nor the README contain this string. `AF_UNIX` is also a good search term.

**Comment by headius** [comment]
PR?

**Comment by neuhaus** [comment]
I don't think you can issue a PR for the project description (which is currently "Unix sockets for java").

**Comment by headius** [comment]
Oh, I thought you meant the README...I'll update the description :-)

**Comment by headius** [comment]
Not really a release item. Fixed!
