### ISSUE TITLE
Make it possible to construct a UNIXSocket or server with existing fd

### ISSUE THREAD

**Issue by headius** [jnr/jnr-unixsocket#4]
For jruby/jruby#940, we need a factory method or constructor method exposed that can take an existing fd.

**Comment by mrbrdo** [comment]
@headius need this for `spring` to work... I can't invoke the `fd, opts` constructor from JRuby. I wasn't even able to do it with `getDeclaredConstructor` (maybe some derp), but I finally managed to totally hack it with `getDeclaredConstructors`. So I know in fact it will work (tested it), just need to expose it to JRuby and use it for `UNIXSocket.for_fd`.

**Comment by headius** [comment]
I'll get something basic in today so we can release this and you can update jruby/jruby#449 to use it.

**Comment by headius** [comment]
jnr-unixsocket 0.10 is released. It will be incorporated into JRuby 9.0.5.0 and is already being used on JRuby master.
