### ISSUE TITLE
Why make Native package access only?

### ISSUE THREAD

**Issue by brettwooldridge** [jnr/jnr-unixsocket#44]
User's should be free to call ``Native.socket(domain, type, protocol)`` etc. without having to copy the class and modify it.

**Comment by ckreiling** [comment]
@brettwooldridge any updates on this? Very interested in the change

**Comment by ckreiling** [comment]
Mostly I'm interested in setting the SockType to `SOCK_SEQPACKET` instead of the current default, `SOCK_STREAM`

**Comment by headius** [comment]
I'd like to do this as a separate jnr-socket project, rather than have jnr-unixsocket start becoming a general purpose BSD Socket API library. Anyone want to assist?
