### ISSUE TITLE
Calling close on a UnixSocket with a pending read waits for the read to time out on Linux

### ISSUE THREAD

**Issue by charleskorn** [jnr/jnr-unixsocket#60]
If you create a `UnixSocket`, set a read timeout and then:

* call `read()` on one thread
* wait a bit and then call `close()` on another thread

...the behaviour is different on OS X and Linux.

On OS X, the read is cancelled as soon as `close()` is called and so `close()` returns immediately. On Linux, the read blocks until the read timeout is reached, and then `close()` returns. 

This makes interrupting read operations impossible, and is the root cause of https://github.com/square/okhttp/issues/4233.

I have created a test case that fails on Linux (but passes on OS X) in https://github.com/charleskorn/jnr-unixsocket/commit/b0981aeb2001fd5367ecceba954106c00e337497.

**Comment by charleskorn** [comment]
I don't know much about sockets programming, but reading https://www.systutorials.com/docs/linux/man/2-close/ suggests that calling `shutdown` on the socket before calling `close` is the correct behaviour. Calling `shutdownInput()` and `shutdownOutput()` in `AbstractNativeSocketChannel.implCloseSelectableChannel()` fixes this.

**Comment by headius** [comment]
@charleskorn Can you propose a PR to fix this?

**Comment by charleskorn** [comment]
Done - #68.

**Comment by selckin** [comment]
This also fixes an issue with docker-maven-plugin for me see https://github.com/fabric8io/docker-maven-plugin/issues/552
