### ISSUE TITLE
Provide JPMS module name

### ISSUE THREAD

**Issue by sbordet** [jnr/jnr-unixsocket#61]
Would be great if a stable JPMS module name can be provided, as simply as adding `Automatic-Module-Name` to the manifest in the jar.

This will allow projects that are moving to proper JPMS modules to reference a stable JPMS name for `jnr-unixsocket` in their `module-info.java`.

I would suggest to not use `com.github` as prefix, but perhaps just `org.jnr`, but it's ultimately your choice.

Thanks!

**Comment by sbordet** [comment]
Also, `jnr-unisocket` has a split package with `jnr-enxio`: `jnr.enxio.channels`.

This makes impossible to use `jnr-unixsocket` as JPMS module, even adding the `Automatic-Module-Name` entry.

**Comment by headius** [comment]
Fixed along with #58.
