### ISSUE TITLE
Solaris can't set socket options

### ISSUE THREAD

**Issue by wolfchimneyrock** [jnr/jnr-unixsocket#91]
Hi, I have encountered an issue on Solaris 5.11 on SPARC-T5 machines using Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
.  I get this exception:

```
java.net.SocketException
        at jnr.unixsocket.UnixSocket.setSoTimeout(UnixSocket.java:277)
Caused by: java.io.IOException: Option not supported by protocol
        at jnr.unixsocket.Common.setSocketOption(Common.java:148)
        at jnr.unixsocket.UnixSocketChannel.setOption(UnixSocketChannel.java:322)
        at jnr.unixsocket.UnixSocket.setSoTimeout(UnixSocket.java:275)
        ... 7 more
```
when I try to change a socket option such as timeout.  code works fine otherwise on Linux-amd64 and AIX-POWER.

The default socket timeout is a ridiculously long time.  Is there any way to change it?

**Comment by headius** [comment]
It seems like we may be using a bad value for one of the parameters to setsockopt within this code:

https://github.com/jnr/jnr-unixsocket/blob/fe79d02b5b4cc59aee5d89515b6bbe54fc6dd25d/src/main/java/jnr/unixsocket/Common.java#L147-L149

The UnixSocketOption value for `SO_RCVTIMEO` used for the `setSoTimeout` is mapped to a value from [jnr-constants](https://github.com/jnr/jnr-constants) at this line of code:

https://github.com/jnr/jnr-unixsocket/blob/fe79d02b5b4cc59aee5d89515b6bbe54fc6dd25d/src/main/java/jnr/unixsocket/Common.java#L157

So at this point I would suspect that the value defined there is not correct for your flavor of Solaris.

I will need some help investigating this! The values in jnr-constants (linked above) are generated from the actual C constants on a given platform. If you look [here](https://github.com/jnr/jnr-constants/blob/master/src/main/java/jnr/constants/platform/solaris/SocketOption.java) you can see the values we are currently using for all Solaris flavors. Can you look into the C socket headers on your system and see if these values match?

If they don't we may finally be forced to split these constants by hardware platform as well as by OS.

The only workaround at this point would be for you to reflectively dig out the file descriptor and call setsockopt yourself with the proper values, either by binding setsockopt on your own (using jnr-ffi, the native binding library behind jnr-unixsocket) or by using reflection to dig into the function already bound by jnr-unixsocket [here](https://github.com/jnr/jnr-unixsocket/blob/aa2c1e43493edc9f6ca2af45a789a7bacbf196a1/src/main/java/jnr/unixsocket/Native.java).

Alternatively, if you are able to give me shell access to a matching environment, I can do the investigation myself.

**Comment by wolfchimneyrock** [comment]
the constants are the same on my `sys/socket.h` as in your `jnr-constants` package:

```
 #define SO_RCVTIMEO 0x1006      /* receive timeout */
```

**Comment by wolfchimneyrock** [comment]
the workaround I have done that works is to switch to non-blocking on the client channel, it is a little more complicated to use but it allows the timeout to be used in the `select()` call.   

Unfortunately we can't give out shell access.  Though I would be happy to do an attempt at `setsockopt()` using reflection

**Comment by wolfchimneyrock** [comment]
When I run the following:
```
        UnixSocketChannel channel = UnixSocketChannel.create();

        try {
            Class<?> nativeClass = Class.forName("jnr.unixsocket.Native");
            Method setsockopt = nativeClass.getDeclaredMethod("setsockopt", int.class, SocketLevel.class, SocketOption.class, int.class);
            setsockopt.setAccessible(true);
            Integer result = (Integer)setsockopt.invoke(null, channel.getFD(), SocketLevel.SOL_SOCKET, SocketOption.SO_RCVTIMEO, 10);
            System.out.println("setsockopt result = " + result);
        } catch (Exception e) {
            e.printStackTrace();
        }
```

on linux/amd64: `setsockopt result = 0`
on AIX/power9:  `setsockopt result = 0`
on Solaris 11.3/sparc: `setsockopt result = -1`

Can you walk me through how I could make custom values of the `SocketLevel` and `SocketOption` ?

**Comment by headius** [comment]
Perhaps the mismatch is in SocketLevel?

https://github.com/jnr/jnr-constants/blob/master/src/main/java/jnr/constants/platform/solaris/SocketLevel.java

It seems that the setsockopt function is being called, but we are getting this error. Another thing you could investigate would be to add code to your println to check the errno value. I suspect it will be EINVAL, though.

```java
System.out.println("errno: " + LastError.getLastError(Runtime.getSystemRuntime()));
```

(untested code but you can see the equivalent here: https://github.com/jnr/jnr-unixsocket/blob/aa2c1e43493edc9f6ca2af45a789a7bacbf196a1/src/main/java/jnr/unixsocket/Native.java#L123

**Comment by wolfchimneyrock** [comment]
`errno = 99`  => `ENOPROTOOPT`

**Comment by wolfchimneyrock** [comment]
If I do the same thing but set `SO_RCVBUF` it works fine

**Comment by wolfchimneyrock** [comment]
I notice the man page for `setsockopt` on Solaris 11.3 doesn't mention `SO_RCVTIMEO`:
https://docs.oracle.com/cd/E86824_01/html/E54774/setsockopt-3socket.html#scrolltoc

whereas the man page for `setsockopt` on Solaris 11.4 does mention it:
https://docs.oracle.com/cd/E88353_01/html/E37843/setsockopt-3c.html#scrolltoc

**Comment by headius** [comment]
So then it is possible this socket option is simply not supported? Maybe there is a different option that has a similar effect?

**Comment by wolfchimneyrock** [comment]
yeah I think thats the case - can't set a timeout for blocking socket read.  Like I said earlier, the work around is to make the channel non-blocking and use a Selector.

**Comment by headius** [comment]
Okay, that is a non-trivial workaround but I'm glad you have something to go forward with. If you are able to determine that there is some other way we can adjust this timeout on earlier versions of solaris, please open a new issue. I will close this issue since there's not much we can do at the moment.
